
start cmd /k ..\x64\Release\DySim.exe HW_SM_MULTI_PL4_MLC_OP0 SW_WL_PL4_GC2_ST WKD_USR60_SEQ SEQ RST_0416_GCRATE_MLC_SEQ

start cmd /k ..\x64\Release\DySim.exe HW_SM_MULTI_PL4_MLC_OP0 SW_WL_PL4_GC2_DY WKD_USR60_SEQ SEQ RST_0416_GCRATE_MLC_SEQ

pause

